Stu_Anlz/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from Anlz_app.views import classroom, students, teachers
from forum.views import contact_us
from Anlz_app import viewss

urlpatterns = [

    path('',viewss.index,name = 'homepage'),
    path('admin/', admin.site.urls),
    path('anlz/', include('Anlz_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    re_path(r'^forum/',include('forum.urls',namespace='forum')),
    re_path(r'^contact_us',contact_us,name='contact'),
    path('', include('django.contrib.flatpages.urls')),
    path('admin1/',classroom.UserListView.as_view(),name='admin_page'),
    path('admin1/approve/<int:pk>/',classroom.approve,name='approve')
]

forum/urls.py
from . import views
from django.urls import re_path

app_name = "forum"
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^thread/(?P<pk>\d+)/$', views.view_thread, name='thread'),
    re_path(r'^thread/(?P<pk>\d+)/add_post/$', views.add_post, name='add_post'),
    re_path(r'^create_forum/$', views.create_forum, name='create_forum'),
    re_path(r'^(?P<pk>\d+)/$', views.forum, name='forum'),
    re_path(r'^(?P<pk>\d+)/add_thread/$', views.add_thread, name='add_thread'),
    re_path(r'^thread/post/(?P<pk>\d+)/comment/$', views.comment, name="comment"),
    re_path(r'^(?P<pk>\d+)/edit/$', views.edit_forum, name="edit_forum"),

]

forum/models.py
from django.db import models
from Anlz_app.models import User
from django.utils import timezone
# Create your models here.
class Forum(models.Model):

    title = models.CharField(max_length=60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User,null=True,on_delete=models.CASCADE)
    description = models.CharField(max_length=255,blank=True )

    def num_post(self):
        return sum([threads.num_post() for threads in self.thread_set.all()])

    def num_threads(self):
        return self.thread_set.count()

    def last_post(self):
        if self.thread_set.count():
            last = None
            for thread in self.thread_set.all():
                l = thread.last_post()
                if l:
                    if not last:
                        last = l
                    elif l.created > last.created:
                        last = l
            return last

    def __str__(self):
        return self.title

class thread(models.Model):
    title = models.CharField(max_length =60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User,blank=True,null=True,on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum,on_delete=models.CASCADE)
    description = models.CharField(max_length =255 ,blank=True)

    def __str__(self):
        return str(self.creator) + " - "  + self.title

    def num_post(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count()

    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by('-created')[0]

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User,blank=True,on_delete=models.CASCADE)
    thread = models.ForeignKey(thread,on_delete=models.CASCADE)
    body = models.TextField(max_length=1000)

    def __str__(self):
        return "{} - {} - {}".format(self.creator,self.thread,self.title)

    def short(self):
        return "{} - {}".format(self.creator,self.title)
    short.allow_tags = True


class Comment(models.Model):
    body = models.TextField(max_length=10000)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    creator = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.body

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    text = models.TextField(max_length=500)

forum/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post,Forum,thread,Comment,Contact

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)

class ThreadForm(forms.ModelForm):

    class Meta:
        model = thread
        fields = ('title','description')

class ForumForm(forms.ModelForm):

    class Meta:
        model  = Forum
        fields = ('title','description')

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'

forum/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from forum.models import Forum, thread, Post,Comment
from Anlz_app.models import User
from .forms import PostForm, ThreadForm,ForumForm,CommentForm,ContactForm
from django.core.paginator import Paginator,InvalidPage,EmptyPage
# Create your views here.
def index(request):
    forums = Forum.objects.order_by('-created')
    forums = make_paginator(request,forums,20)
    context_dict = {'forums' : forums}
    return render (request, 'forum/index.html',context_dict)

def forum(request, pk):
    """
    Listing all threads in a forum with pk=pk.
    """
    forum = get_object_or_404(Forum, pk=pk)
    threads = thread.objects.filter(forum=pk).order_by('-created')
    threads =  make_paginator(request, threads, 20)
    context_dict = {'threads': threads, 'forum': forum}
    return render(request, 'forum/forum.html', context_dict)

def view_thread(request, pk):
    """
    List posts in this thread.
    """
    # get_object_or_404 ?? get_list_or_404?? Or just no error handling at all here???
    try:
        posts = Post.objects.filter(thread=pk).order_by('created')
    except:
        raise Http404

    posts = make_paginator(request, posts, 15)
    threads = get_object_or_404(thread, pk=pk)

    # Get all comments associated with posts in this thread.
    comments = [com for com in Comment.objects.all() if com.post.thread.pk == threads.pk]
    context_dict = {'posts': posts, 'thread': threads, 'comments': comments}
    return render(request, 'forum/thread.html', context_dict)


@login_required
def add_thread(request,pk):
    forum = get_object_or_404(Forum,pk=pk)
    if request.method == 'POST':
        threads = thread(forum = forum)
        form = ThreadForm(request.POST,instance=threads)
        if form.is_valid():
            threads = form.save(commit=False)
            # # user =request.User.get_username()
            threads.creator = request.user
            # print(request.User)
            threads.save()
            return redirect('forum:forum',pk=pk)
    else:
            form = ThreadForm()
    context_dict = {'form': form, 'forum':forum}
    return render(request,'forum/add_thread.html',context_dict)


@login_required
def add_post(request,pk):
    threads =get_object_or_404(thread,pk=pk)
    if request.method == 'POST':
        post = Post(thread=threads)
        form = PostForm(request.POST,instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.creator = request.user
            post.save()
            # profile = User.objects.get(username=post.creator)
            # profile.posts = profile.posts + 1
            # profile.save()
            return redirect('forum:thread',pk=pk)
        else:
            print(form.errors)
    else:
        form = PostForm()
    context_dict = {'form': form, 'thread': threads}
    return render(request, 'forum/add_post.html',context_dict)



def make_paginator(request, items, number):
    '''
    Make a paginator of number items of type 'item'
    '''
    paginator = Paginator(items, number)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        items = paginator.page(page)
    except(InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)

    return items

@login_required
def create_forum(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.creator = request.user
            forum.save()
            return redirect('forum:index')
        else:
            print(form.errors)
    else:
        form = ForumForm()
    return render(request,'forum/create_forum.html',{'forum':form})

@login_required
def comment(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        comment = Comment(post=post)
        comment_form = CommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.creator = request.user
            comment.save()
            return redirect('forum:thread',pk=post.thread_id)
    else:
            comment_form =CommentForm()
            context_dict = {'post':post ,'form':comment_form }
            return render(request,'forum/add_comment.html',context_dict)

@login_required
def edit_forum(request,pk):
    forum = get_object_or_404(Forum , pk=pk)
    if request.method == 'POST':
        form = ForumForm(request.POST, instance=forum)
        if form.is_valid():
            forum = form.save(commit=False)
            forum.creator = request.user
            forum.save()
            return redirect('forum:forum',pk=pk)
    else:
        form = ForumForm(instance=forum)
    context_dict = {'form':form,'forum':forum}
    return render(request,'forum/edit_forum.html',context_dict)


def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request, 'Your suggestion is submitted')
            return redirect('contact_us.html')
    else:
        form = ContactForm()
        return render(request,'contact_us.html',{'form':form})

forum/templates/forum/add_comment.html
{% extends "base2.html" %}

{% load static %}

{% block title %}
    | Comment :: {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container row">
        <div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">
            <form action="{% url 'forum:comment' pk=post.pk %}" method="post">
                {% csrf_token %}
                {% if form.errors %}
                    {{ form.errors }}
                {% endif %}


                <div class="form-group">
                    <label for="id_body">Content</label>
                    <textarea class="form-control" rows="5" id="id_body" placeholder="Your Comment." name="body"></textarea>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            </form>

            <div class="pull-left" style="clear: both">
                <a href="{% url 'forum:thread' pk=post.thread.pk %}">&laquo; Back to topic.</a>
            </div>
        </div>
    </div>
{% endblock %}

forum/templates/forum/add_post.html
{% extends "base2.html" %}
{% load static %}

{% if thread %}
    {% block title %}
        | Re: {{ thread.title }}
    {% endblock title %}
{% endif %}

{% block content %}
    <br>
    <div class="container row">
        <div class="col-sm-8 col-sm-offset-2">
            <form action="{% url 'forum:add_post' pk=thread.pk %}" method="POST" class="form-horizontal" role="form">
                {% csrf_token %}
                <div class="form-group">
                    <legend><h2> {{ thread.title }}</h2></legend>
                </div>

                <div class="form-group">
                    <div class="col-sm-2">
                        <label for="id_title" class="control-label">Post Title: </label>
                    </div>
                    <div class="col-sm-10">
                        <input type="text" id="id_title" name="title" maxlength="60" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-2">
                        <label for="id_body" class="control-label">Post Content: </label>
                    </div>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="id_body" cols="40" rows="10" maxlength="10000" name="body" placeholder="Reply..."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="pull-left">
        <a href="{% url 'forum:thread' pk=thread.pk %}">&laquo; Back to topic.</a>
    </div>
{% endblock content %}

forum/templates/forum/add_thread.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <div class="container col-md-10 col-md-offset-1">
        <form role="form" action="{% url 'forum:add_thread' pk=forum.pk %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <legend>Start a topic in {{ forum.title }}</legend>
            </div>
            <div class="form-group">
                <label for="id_title">Topic</label>
                {% if form.errors %}
                    <div class="alert alert-danger">
                        <p>This field is required.</p>
                    </div>
                {% endif %}
                <input type="text" id="id_title" maxlength="60" name="title" class="form-control">
            </div>

             <div class="form-group">
                <label for="id_description">Question</label>
                <textarea class="form-control" maxlength="255" rows="3" id="id_description" name="description" placeholder="A short description of the topic"></textarea>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
        <div class="row" style="clear: both">
            <div class="pull-left">
                <a href="{% url 'forum:forum' pk=forum.pk %}">&laquo; Back to forum.</a>
            </div>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/create_forum.html
{% extends "base2.html" %}
{% load static %}

<h2>Create Forum</h2>


{% block content %}
    <div class="container">
        <br>
        <form role="form" method="post" action="{% url 'forum:create_forum' %}">
            {% csrf_token %}
            <div class="form-group">
                <legend>Create Forum</legend>
            </div>
            <div class="form-group">
                <label for="id_title">Subject</label>
                <input class="form-control" id="id_title" name="title" maxlength="60" type="text" placeholder="Title">
            </div>

            <div class="form-group">
                <label for="id_description">Description</label>
                <textarea class="form-control" maxlength="255" rows="3" id="id_description" name="description" placeholder="A short description of the forum"></textarea>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>

        <div class="pull-left" style="clear: both">
            <a href="{% url 'forum:index' %}">&laquo; Back to forums.</a>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/edit_forum.html
{% extends "base2.html" %}
{% load static %}



{% block content %}
    <div class="container col-md-8 col-md-offset-2">
        <br>
        <form role="form" method="post" action="{% url 'forum:edit_forum' pk=forum.pk %}" id="form-content" class="threadforum">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Submit</button>

        </form>

        <div class="pull-left" style="clear: both">
            <a href="{% url 'forum:index' %}">&laquo; Back to forums.</a>
        </div>
    </div>
{% endblock content %}

forum/templates/forum/forum.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>
                <span class="content-title">{{ forum.title }}</span>
                <br>
                {% if forum.description %}
                    <small>{{ forum.description }}</small>
                {% else %}
                    <small><em>No description available.</em></small>
                {% endif %}
            </h1>
            <div>
                <small>Created by: {{ forum.creator }}</small> <br>
                <small>Created On: {{ forum.created }}</small>
            </div>
            {% if user.is_authenticated %}
                <span>
                    <a href="{% url 'forum:add_thread' pk=forum.pk %}" class="btn btn-primary start-new-btn">New Topic</a>
                </span>
            {% endif %}
            {% if user.is_authenticated and user == forum.creator %}
                <br>
                <span><a href={% url 'forum:edit_forum' pk=forum.pk %}>Edit forum title or description</a></span>
            {% endif %}
        </div>
        <br>
        <div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <th><h3 class="text-center">Topics</h3></th>
                    <th><h3 class="text-center">Replies</h3></th>
                    <th><h3 class="text-center">Last Post</h3></th>
                    <th></th>
                </thead>
                <tbody>
                    {% if threads %}
                        {% for thread in threads %}
                            <tr>
                                <td>
                                    <h4>
                                        <a href="{% url 'forum:thread' pk=thread.pk %}">{{ thread.title }}</a><br>
                                        {% if thread.description %}
                                            <small>{{ thread.description }}</small>
                                        {% else %}
                                            <small><em>No description available.</em></small>
                                        {% endif %}
                                        <br>
                                        <!-- <small>
                                            Started by: {{ thread.creator }}<br>
                                            On: {{ thread.created }}
                                        </small> -->
                                    </h4>
                                </td>
                                <td class="text-center">{{ thread.num_replies }}</td>
                                <td><small>{{ thread.last_post.short|linebreaks }}{{ thread.last_post.created }}</small></td>
                                <td class="text-center">
                                    <a href="{% url 'forum:thread' pk=thread.pk %}" class="btn btn-link">View</a>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="4" class="text-center"><em>No threads in this forum. Check later or add a new topic.</em></td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <div class="pull-left" style="clear: both">
            <a href="{% url 'forum:index' %}">&laquo; Back to forums.</a>
        </div>
    </div>

    {% if threads %}
        <div class="row" style="clear: both">
            <span class="step-links">
                <ul class="pager">
                    <div class="col-xs-4">
                        {% if threads.has_previous %}
                            <li class="previous">
                                <a href="?page={{ threads.previous_page_number }}">&larr; Newer</a>
                            </li>
                        {% endif %}
                    </div>
                    <div class="col-xs-4">
                        <li class="active">
                            <a href="#!">{{ threads.number }} / {{ threads.paginator.num_pages }}</a>
                        </li>
                    </div>
                    <div class="col-xs-4">
                        {% if threads.has_next %}
                            <li class="next">
                                <a href="?page={{ threads.next_page_number }}">Older &rarr;</a>
                            </li>
                        {% endif %}
                    </div>
                </ul>
            </span>
        </div>
    {% endif %}

{% endblock content %}

forum/templates/forum/index.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <div class="main">
        <!-- forums -->
        <div class="jumbotron">
            <h1 class="page-header">Discussion Form<small><h3>Discuss what you want.</h3></small></h1>
            <h4>Choose a forum of your interest.</h4>
            {% if user.is_authenticated and user.is_teacher %}
                <span class="pull-right">
                    <a href="{% url 'forum:create_forum' %}" class="btn btn-primary start-new-btn"> Create Forum</a>
                </span>
            {% endif %}
        </div>
        <div class="container row">
            <div class="col-sm-10 col-sm-offset-1">
                <table class="table table-striped table-bordered table-hover container">
                    <thead>
                        <th><h3 class="text-center">Forum</h3></th>
                        <th><h3 class="text-center">Topic Threads</h3></th>
                        <th><h3>Posts</h3></th>
                        <th><h3 class="text-center">Last Post</h3></th>
                        <th></th>
                    </thead>
                    {% if forums %}
                        {% for forum in forums %}
                            <tr>
                                <td>
                                    <h4>
                                        <a href="{% url 'forum:forum' pk=forum.pk %}">{{ forum.title }}</a> <br>
                                        <small>
                                            {% if forum.description %}
                                                <em>{{ forum.description }}</em>
                                            {% else %}
                                                <em>No description available.</em>
                                            {% endif %}
                                            <br>
                                            Created: {{ forum.created }} <br>
                                            By: {{ forum.creator }}
                                        </small>
                                    </h4>
                                </td>
                                <td class="text-center">{{ forum.num_threads }}</td>
                                <td class="text-center">{{ forum.num_post }}</td>
                                <td><small>{{ forum.last_post.short | linebreaks }} {{ forum.last_post.created }}</small></td>
                                <td class="text-center"><a href="{% url 'forum:forum' pk=forum.pk %}" class="btn btn-link">View</a></td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="5" class="text-center"><em>No forums yet...</em></td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </div>
{% if forums %}
    <div class="row" style="clear: both">
        <span class="step-links">
            <ul class="pager">
                <div class="col-xs-4">
                    {% if forums.has_previous %}
                        <li class="previous">
                            <a href="?page={{ forums.previous_page_number }}">&larr; Newer</a>
                        </li>
                    {% endif %}
                </div>
                <div class="col-xs-4">
                    <li class="active">
                        <a href="#!">{{ forums.number }} / {{ forums.paginator.num_pages }}</a>
                    </li>
                </div>
                <div class="col-xs-4">
                    {% if forums.has_next %}
                        <li class="next">
                            <a href="?page={{ forums.next_page_number }}">Older &rarr;</a>
                        </li>
                    {% endif %}
                </div>
            </ul>
        </span>
    </div>
{% endif %}
{% endblock %}

forum/templates/forum/thread.html
{% extends "base2.html" %}

{% load static %}



{% block content %}
    <div class="container">
        {% if thread %}
            <div class="page-header">
                <h1 class="content-title">
                    <span id="thread-title">{{ thread.title }}</span>
                    {% if thread.description %}
                        <br>
                        <span id="thread-description"><small>{{ thread.description }}</small></span>
                    {% else %}
                        <br>
                        <small><em>No description available.</em></small>
                    {% endif %}
                </h1>
                <div>
                    <small>Created by: {{ thread.creator }}</small> <br>
                    <small>Created On: {{ thread.created }}</small>
                </div>
                <br>
                {% if user.is_authenticated %}
                    <div class="pull-right">
                        <a href="{% url 'forum:add_post' pk=thread.pk %}" class="pull-right btn btn-primary start-new-btn">New Post</a>
                    </div>
                {% endif %}

                </div>
        {% endif %}
        <div class="col-xs-12 col-md-10 col-md-offset-1">
            {% if posts %}
                {% for post in posts %}
                <hr>
              <!--  -->

                            <div class="card border-primary mb-3 p-3 mb-2 bg-light text-dark">
                              <div class="card-body">
                                <p class="card-text"><small class="text-muted">By: {{ post.creator }} on <u> {{ post.created }} </u></small></p>

                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.body }}</p>
                              </div>


<!--  -->

                            <div>
                                <span>
                                 <a href="{% url 'forum:comment' pk=post.pk %}" class="btn btn-link">  <button type="button" class="btn btn-primary">Reply</button> </a>
                                 <button class="btn btn-primary" size= type="button" data-toggle="collapse" data-target="#demo{{ forloop.counter }}" aria-expanded="false" aria-controls="collapseExample">
                                   View comments
                                 </button>
                                </span>
                            </div>




                            <div class="collapse" id="demo{{ forloop.counter }}">
                              <div class="card card-body">

                            {% if comments %}
                                <h4 class="page-header content-title">Comments</h4>
                                {% for comment in comments %}
                                    {% if comment.post.pk == post.pk %}
                                    <div class="card border-secondary mb-3 l-22" style="max-width: 40rem;">
                                      <div class="card-header text-primary font-weight-bold">{{ comment.creator }}</div>
                                      <div class="card-body">
                                      <p class="card-text">{{ comment.body }}</p>
                                        </div>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}

                      </div>
                    </div>
                  </div>
                {% endfor %}
            {% else %}
                <div class="well well-lg">
                    <h3>No posts about this yet.</h3>
                    {% if user.is_authenticated %}
                        <p>You can post something <a href="{% url 'forum:add_post' pk=thread.pk %}">here.</a></p>

                    {% endif %}
                </div>
            {% endif %}
            <div class="pull-left" style="clear: both">
                <a href="{% url 'forum:forum' pk=thread.forum.pk %}">&laquo; Back to thread.</a>
            </div>
        </div>
    </div>
    {% if posts %}
        <div class="row" style="clear: both">
            <span class="step-links">
                <ul class="pager">
                    <div class="col-xs-4">
                        {% if posts.has_previous %}
                            <li class="previous">
                                <a href="?page={{ posts.previous_page_number }}">&larr; Newer</a>
                            </li>
                        {% endif %}
                    </div>
                    <div class="col-xs-4">
                        <li class="active">
                            <a href="#">{{ posts.number }} / {{ posts.paginator.num_pages }}</a>
                        </li>
                    </div>
                    <div class="col-xs-4">
                        {% if posts.has_next %}
                            <li class="next">
                                <a href="?page={{ posts.next_page_number }}">Older &rarr;</a>
                            </li>
                        {% endif %}
                    </div>
                </ul>
            </span>
          </div>



    {% endif %}

{% endblock content %}