Anlz_app/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('taken/<int:pk>/results/',students.view_results,name='results'),
        path('taken/<int:pk>/results/charts/',students.results_graph,name='charts'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('students/activate',teachers.StudentListView.as_view(),name='new_student'),
        path('students/activate/<int:pk>/',teachers.approve,name='approve'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('subject/', teachers.SubjectListView.as_view(), name='sub_list'),
        path('subject/add/',teachers.SubjectCreateView.as_view(),name = 'sub_add'),
        path('subject/del/<int:pk>/',teachers.SubjectDeleteView.as_view(),name = 'sub_del'),
    ], 'classroom'), namespace='teachers')),
]

Stu_Anlz/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from Anlz_app.views import classroom, students, teachers
from forum.views import contact_us
from Anlz_app import viewss

urlpatterns = [

    path('',viewss.index,name = 'homepage'),
    path('admin/', admin.site.urls),
    path('anlz/', include('Anlz_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    re_path(r'^forum/',include('forum.urls',namespace='forum')),
    re_path(r'^contact_us',contact_us,name='contact'),
    path('', include('django.contrib.flatpages.urls')),
    path('admin1/',classroom.UserListView.as_view(),name='admin_page'),
    path('admin1/approve/<int:pk>/',classroom.approve,name='approve')
]

forum/urls.py
from . import views
from django.urls import re_path

app_name = "forum"
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^thread/(?P<pk>\d+)/$', views.view_thread, name='thread'),
    re_path(r'^thread/(?P<pk>\d+)/add_post/$', views.add_post, name='add_post'),
    re_path(r'^create_forum/$', views.create_forum, name='create_forum'),
    re_path(r'^(?P<pk>\d+)/$', views.forum, name='forum'),
    re_path(r'^(?P<pk>\d+)/add_thread/$', views.add_thread, name='add_thread'),
    re_path(r'^thread/post/(?P<pk>\d+)/comment/$', views.comment, name="comment"),
    re_path(r'^(?P<pk>\d+)/edit/$', views.edit_forum, name="edit_forum"),

]

Anlz_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from Anlz_app.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User)


class TeacherSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,required = True)
    last_name = forms.CharField(max_length=100,required = True)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','first_name','last_name','email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active=False
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    first_name = forms.CharField(max_length=100,required = True)
    last_name = forms.CharField(max_length=100,required = True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','first_name','last_name','email')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.is_active = False
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user


class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Question
        fields = ('text','level' )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name','color' )
        widgets = {

                'color':forms.TextInput(attrs={'type':'color'})
            }

Anlz_app/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic import ListView
from ..models import  User
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
class SignUpView(TemplateView):
    template_name = 'registration/signup.html'
@method_decorator([staff_member_required],name='dispatch')
class UserListView(ListView):
    model=User
    context_object_name = 'User'
    template_name = 'admin_page.html'

def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        elif request.user.is_student:
            return redirect('students:quiz_list')
        else:
            return redirect('admin_page')
    return render(request, 'base2.html')

@staff_member_required
def approve(request, pk):

    user = User.objects.get(id=pk)
    user.is_active = True
    user.save()
    return HttpResponse("Teacher's account Activated")

Anlz_app/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from django.utils.timezone import datetime
from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm
from ..models import Quiz, Student, TakenQuiz, User
from random import Random
import random
from django.db.models import Case, Count, When
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Contact your teacher to activate your account before logging in')
        return redirect('login')


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(subject__in=student_interests) \
                .exclude(pk__in=taken_quizzes) \
                .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset

@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    random.seed(student)

    answered_questions_lev = student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True)
    correct_question_lev = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__question__level', flat=True))
    answer_questions_lev = list(student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True))
    answers = list(student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__id', flat=True))
    correct_answers = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__id', flat=True))
    total_questions = quiz.quiz_total_questions
    print(correct_question_lev)
    if len(answers)==0:
        lev = 3;
    else:
        lev = answered_questions_lev.last()
        print(lev)
    unanswered_questions = student.get_unanswered_questions(quiz,answers,correct_answers,lev)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round((((total_questions-len(answers)) - 1) / total_questions) * 100)
    question = unanswered_questions.first()
    # print(answer_questions)
    print('total=',total_questions)
    print(answers)
    print(correct_answers)
    print(len(answers))
    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():

            with transaction.atomic():

                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()

                if student.get_unanswered_questions(quiz,answers,correct_answers,lev).exists() and len(answers)+1<total_questions:
                    return redirect('students:take_quiz', pk)
                elif len(answers)+1>=total_questions:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    score=0;
                    for i in correct_question_lev:
                        if i==1:
                            score = score +1;
                        if i==2:
                            score = score +2;
                        if i==3:
                            score = score +3;
                        if i==4:
                            score = score +6;
                        if i==5:
                            score = score +9;
                    total_score=0
                    for i in answer_questions_lev:
                        if i==1:
                            total_score = total_score +1;
                        if i==2:
                            total_score = total_score +2;
                        if i==3:
                            total_score = total_score +3;
                        if i==4:
                            total_score = total_score +6;
                        if i==5:
                            total_score = total_score +9;
                    percentage = round((score/total_score * 100),2)
                    view_results(request,pk=pk)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=percentage,total_marks=total_score,obtained_marks=score)


                    return redirect('students:results',pk=pk)
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'classroom/students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress
    })

@login_required
@student_required
def view_results(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student
    user = request.user

    answered_questions_lev = student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True)
    correct_question_lev = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__question__level', flat=True))
    answer_questions_lev = list(student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True))
    answerss = list(student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__id', flat=True))
    correct_answers = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__id', flat=True))
    answered_questions = student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__question__text', flat=True)
    correct_ques = student.quiz_answers.filter(answer__question__quiz=quiz,answer__is_correct=True).values_list('answer__question__text', flat=True)
    answers = student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__text', flat=True)
    score=0;
    for i in correct_question_lev:
        if i==1:
            score = score +1;
        if i==2:
            score = score +2;
        if i==3:
            score = score +3;
        if i==4:
            score = score +6;
        if i==5:
            score = score +9;
    total_score=0
    for i in answer_questions_lev:
        if i==1:
            total_score = total_score +1;
        if i==2:
            total_score = total_score +2;
        if i==3:
            total_score = total_score +3;
        if i==4:
            total_score = total_score +6;
        if i==5:
            total_score = total_score +9;
    print(answerss)
    print(correct_answers)
    check = list(set(answerss).intersection(correct_answers))
    print(check)
    Marks = []
    marks_graph=[]
    for x,y in zip(answerss,answer_questions_lev):
        if x in check:
            if y==1:
                Marks.append('+1')
            elif y ==2:
                Marks.append('+2')
            elif y ==3:
                Marks.append('+3')
            elif y ==4:
                Marks.append('+6')
            elif y ==5:
                Marks.append('+9')
        elif x not in check:
            Marks.append('+0')
    fname = user.first_name
    lname = user.last_name
    username = user.username
    quiz = quiz.name
    print(quiz)
    total_ques = len(answers)

    percentage = round((score/total_score * 100),2)
    print(Marks)
    if percentage <= 32.0:
        messages.warning(request, 'Your obtained marks in %s was %s out of %s marks.' % (quiz, score,total_score))
    elif percentage <= 60 and percentage>32:
        messages.success(request, 'You completed the quiz %s with second division! You obtained marks was %s out of %s marks.' % (quiz, score,total_score))
    elif percentage <= 80 and percentage>60:

Anlz_app/templates/classroom/teachers/activate_students.html
{% extends 'base2.html' %}

{% block content %}

  <h2 class="mb-3">Activate students</h2> <p>Click on any username to activate the student.</p>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Newly Registered Students</th>

          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for users in User.all %}
        {% if users.is_student %}
        {% if not users.is_active %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:approve' pk=users.pk %}">{{users.username}}</a></td>
          {% endif %}
          {% endif %}
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">No users</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Anlz_app/templates/classroom/teachers/question_add_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

Anlz_app/templates/classroom/teachers/question_change_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>10</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
    <a href="{% url 'teachers:question_delete' quiz.pk question.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
{% endblock %}

Anlz_app/templates/classroom/teachers/question_delete_confirm.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Cancel</a>
  </form>
{% endblock %}

Anlz_app/templates/classroom/teachers/quiz_add_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new test</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new test</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

Anlz_app/templates/classroom/teachers/quiz_change_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ quiz.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ quiz.name }}
    <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'teachers:quiz_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        <a href="{% url 'teachers:quiz_delete' quiz.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card-footer">
    <a href="{% url 'teachers:question_add' quiz.pk %}" class="btn btn-primary btn-sm">Add question</a>
  </div>
  <div class="card">
    <div class="card-header">
        <div class="row">
        <div class="col-9">
          <strong>Questions</strong>
        </div>
        <div class="col-1">
          <strong>Level</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-9">
              <a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-1">
              {{ question.level }}
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>

          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teachers:question_add' quiz.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>

  </div>
{% endblock %}

Anlz_app/templates/classroom/teachers/quiz_change_list.html
{% extends 'base2.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Tests</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Tests</h2>
  <a href="{% url 'teachers:quiz_add' %}" class="btn btn-primary mb-3" role="button">Add test</a>
  <a href="{% url 'teachers:sub_list' %}" class="btn btn-primary mb-3" role="button">Your Subjects</a>
  <a href="{% url 'teachers:new_student' %}" class="btn btn-primary mb-3" role="button">Activate Students</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Test</th>
          <th>Subject</th>
          <th>Questions</th>
          <th>Taken</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }}</td>
            <td class="align-middle">{{ quiz.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any test yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Anlz_app/templates/classroom/teachers/subject_list.html
{% extends 'base2.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Tests</a></li>
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'teachers:sub_list'%}">Subjects</a></li>

  </ol>
</nav>
  <h2 class="mb-3">Add or delete subjects</h2> <p>Click on any subject to delete it.</p>
    <a href="{% url 'teachers:sub_add' %}" class="btn btn-primary mb-3" role="button">Add Subject</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Subject</th>

          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for sub in subjects.all %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:sub_del' pk=sub.pk %}">{{ sub.name }}</a></td>

          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any subjects yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}