Anlz_app/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('taken/<int:pk>/results/',students.view_results,name='results'),
        path('taken/<int:pk>/results/charts/',students.results_graph,name='charts'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('students/activate',teachers.StudentListView.as_view(),name='new_student'),
        path('students/activate/<int:pk>/',teachers.approve,name='approve'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('subject/', teachers.SubjectListView.as_view(), name='sub_list'),
        path('subject/add/',teachers.SubjectCreateView.as_view(),name = 'sub_add'),
        path('subject/del/<int:pk>/',teachers.SubjectDeleteView.as_view(),name = 'sub_del'),
    ], 'classroom'), namespace='teachers')),
]

Stu_Anlz/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from Anlz_app.views import classroom, students, teachers
from forum.views import contact_us
from Anlz_app import viewss

urlpatterns = [

    path('',viewss.index,name = 'homepage'),
    path('admin/', admin.site.urls),
    path('anlz/', include('Anlz_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    re_path(r'^forum/',include('forum.urls',namespace='forum')),
    re_path(r'^contact_us',contact_us,name='contact'),
    path('', include('django.contrib.flatpages.urls')),
    path('admin1/',classroom.UserListView.as_view(),name='admin_page'),
    path('admin1/approve/<int:pk>/',classroom.approve,name='approve')
]

forum/urls.py
from . import views
from django.urls import re_path

app_name = "forum"
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^thread/(?P<pk>\d+)/$', views.view_thread, name='thread'),
    re_path(r'^thread/(?P<pk>\d+)/add_post/$', views.add_post, name='add_post'),
    re_path(r'^create_forum/$', views.create_forum, name='create_forum'),
    re_path(r'^(?P<pk>\d+)/$', views.forum, name='forum'),
    re_path(r'^(?P<pk>\d+)/add_thread/$', views.add_thread, name='add_thread'),
    re_path(r'^thread/post/(?P<pk>\d+)/comment/$', views.comment, name="comment"),
    re_path(r'^(?P<pk>\d+)/edit/$', views.edit_forum, name="edit_forum"),

]

Anlz_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError

from Anlz_app.models import (Answer, Question, Student, StudentAnswer,
                              Subject, User)


class TeacherSignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100,required = True)
    last_name = forms.CharField(max_length=100,required = True)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','first_name','last_name','email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active=False
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    interests = forms.ModelMultipleChoiceField(
        queryset=Subject.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    first_name = forms.CharField(max_length=100,required = True)
    last_name = forms.CharField(max_length=100,required = True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','first_name','last_name','email')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.is_active = False
        user.save()
        student = Student.objects.create(user=user)
        student.interests.add(*self.cleaned_data.get('interests'))
        return user


class StudentInterestsForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('interests', )
        widgets = {
            'interests': forms.CheckboxSelectMultiple
        }


class QuestionForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Question
        fields = ('text','level' )


class BaseAnswerInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        super().clean()

        has_one_correct_answer = False
        for form in self.forms:
            if not form.cleaned_data.get('DELETE', False):
                if form.cleaned_data.get('is_correct', False):
                    has_one_correct_answer = True
                    break
        if not has_one_correct_answer:
            raise ValidationError('Mark at least one answer as correct.', code='no_correct_answer')


class TakeQuizForm(forms.ModelForm):
    answer = forms.ModelChoiceField(
        queryset=Answer.objects.none(),
        widget=forms.RadioSelect(),
        required=True,
        empty_label=None)

    class Meta:
        model = StudentAnswer
        fields = ('answer', )

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question')
        super().__init__(*args, **kwargs)
        self.fields['answer'].queryset = question.answers.order_by('text')

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ('name','color' )
        widgets = {

                'color':forms.TextInput(attrs={'type':'color'})
            }

Anlz_app/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic import ListView
from ..models import  User
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse
class SignUpView(TemplateView):
    template_name = 'registration/signup.html'
@method_decorator([staff_member_required],name='dispatch')
class UserListView(ListView):
    model=User
    context_object_name = 'User'
    template_name = 'admin_page.html'

def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:quiz_change_list')
        elif request.user.is_student:
            return redirect('students:quiz_list')
        else:
            return redirect('admin_page')
    return render(request, 'base2.html')

@staff_member_required
def approve(request, pk):

    user = User.objects.get(id=pk)
    user.is_active = True
    user.save()
    return HttpResponse("Teacher's account Activated")

Anlz_app/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from django.utils.timezone import datetime
from ..decorators import student_required
from ..forms import StudentInterestsForm, StudentSignUpForm, TakeQuizForm
from ..models import Quiz, Student, TakenQuiz, User
from random import Random
import random
from django.db.models import Case, Count, When
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Contact your teacher to activate your account before logging in')
        return redirect('login')


@method_decorator([login_required, student_required], name='dispatch')
class StudentInterestsView(UpdateView):
    model = Student
    form_class = StudentInterestsForm
    template_name = 'classroom/students/interests_form.html'
    success_url = reverse_lazy('students:quiz_list')

    def get_object(self):
        return self.request.user.student

    def form_valid(self, form):
        messages.success(self.request, 'Interests updated with success!')
        return super().form_valid(form)


@method_decorator([login_required, student_required], name='dispatch')
class QuizListView(ListView):
    model = Quiz
    ordering = ('name', )
    context_object_name = 'quizzes'
    template_name = 'classroom/students/quiz_list.html'

    def get_queryset(self):
        student = self.request.user.student
        student_interests = student.interests.values_list('pk', flat=True)
        taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Quiz.objects.filter(subject__in=student_interests) \
                .exclude(pk__in=taken_quizzes) \
                .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset

@login_required
@student_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    random.seed(student)

    answered_questions_lev = student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True)
    correct_question_lev = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__question__level', flat=True))
    answer_questions_lev = list(student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True))
    answers = list(student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__id', flat=True))
    correct_answers = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__id', flat=True))
    total_questions = quiz.quiz_total_questions
    print(correct_question_lev)
    if len(answers)==0:
        lev = 3;
    else:
        lev = answered_questions_lev.last()
        print(lev)
    unanswered_questions = student.get_unanswered_questions(quiz,answers,correct_answers,lev)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round((((total_questions-len(answers)) - 1) / total_questions) * 100)
    question = unanswered_questions.first()
    # print(answer_questions)
    print('total=',total_questions)
    print(answers)
    print(correct_answers)
    print(len(answers))
    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():

            with transaction.atomic():

                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()

                if student.get_unanswered_questions(quiz,answers,correct_answers,lev).exists() and len(answers)+1<total_questions:
                    return redirect('students:take_quiz', pk)
                elif len(answers)+1>=total_questions:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    score=0;
                    for i in correct_question_lev:
                        if i==1:
                            score = score +1;
                        if i==2:
                            score = score +2;
                        if i==3:
                            score = score +3;
                        if i==4:
                            score = score +6;
                        if i==5:
                            score = score +9;
                    total_score=0
                    for i in answer_questions_lev:
                        if i==1:
                            total_score = total_score +1;
                        if i==2:
                            total_score = total_score +2;
                        if i==3:
                            total_score = total_score +3;
                        if i==4:
                            total_score = total_score +6;
                        if i==5:
                            total_score = total_score +9;
                    percentage = round((score/total_score * 100),2)
                    view_results(request,pk=pk)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=percentage,total_marks=total_score,obtained_marks=score)


                    return redirect('students:results',pk=pk)
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'classroom/students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,
        'progress': progress
    })

@login_required
@student_required
def view_results(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student
    user = request.user

    answered_questions_lev = student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True)
    correct_question_lev = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__question__level', flat=True))
    answer_questions_lev = list(student.quiz_answers \
        .filter(answer__question__quiz=quiz) \
        .values_list('answer__question__level', flat=True))
    answerss = list(student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__id', flat=True))
    correct_answers = list(student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).values_list('answer__id', flat=True))
    answered_questions = student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__question__text', flat=True)
    correct_ques = student.quiz_answers.filter(answer__question__quiz=quiz,answer__is_correct=True).values_list('answer__question__text', flat=True)
    answers = student.quiz_answers.filter(answer__question__quiz=quiz).values_list('answer__text', flat=True)
    score=0;
    for i in correct_question_lev:
        if i==1:
            score = score +1;
        if i==2:
            score = score +2;
        if i==3:
            score = score +3;
        if i==4:
            score = score +6;
        if i==5:
            score = score +9;
    total_score=0
    for i in answer_questions_lev:
        if i==1:
            total_score = total_score +1;
        if i==2:
            total_score = total_score +2;
        if i==3:
            total_score = total_score +3;
        if i==4:
            total_score = total_score +6;
        if i==5:
            total_score = total_score +9;
    print(answerss)
    print(correct_answers)
    check = list(set(answerss).intersection(correct_answers))
    print(check)
    Marks = []
    marks_graph=[]
    for x,y in zip(answerss,answer_questions_lev):
        if x in check:
            if y==1:
                Marks.append('+1')
            elif y ==2:
                Marks.append('+2')
            elif y ==3:
                Marks.append('+3')
            elif y ==4:
                Marks.append('+6')
            elif y ==5:
                Marks.append('+9')
        elif x not in check:
            Marks.append('+0')
    fname = user.first_name
    lname = user.last_name
    username = user.username
    quiz = quiz.name
    print(quiz)
    total_ques = len(answers)

    percentage = round((score/total_score * 100),2)
    print(Marks)
    if percentage <= 32.0:
        messages.warning(request, 'Your obtained marks in %s was %s out of %s marks.' % (quiz, score,total_score))
    elif percentage <= 60 and percentage>32:
        messages.success(request, 'You completed the quiz %s with second division! You obtained marks was %s out of %s marks.' % (quiz, score,total_score))
    elif percentage <= 80 and percentage>60:

Anlz_app/templates/classroom/students/_header.html
<h2>Tests</h2>
<p class="text-muted">
  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>
</p>

<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'students:quiz_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'taken' %} active{% endif %}" href="{% url 'students:taken_quiz_list' %}">Taken</a>
  </li>
</ul>

Anlz_app/templates/classroom/students/interests_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2 class="mb-3">Update your interests</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'students:quiz_list' %}" class="btn btn-outline-secondary">Cancel</a>
  </form>
{% endblock %}

Anlz_app/templates/classroom/students/quiz_list.html
{% extends 'base2.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='new' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Test</th>
          <th>Subject</th>
          <th>Length</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for quiz in quizzes %}
          <tr>
            <td class="align-middle">{{ quiz.name }}</td>
            <td class="align-middle">{{ quiz.subject.get_html_badge }}</td>
            <td class="align-middle">{{ quiz.questions_count }} questions</td>
            <td class="text-right">
              <a href="{% url 'students:take_quiz' quiz.pk %}" class="btn btn-primary">Start Test</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No test matching your interests right now.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

Anlz_app/templates/classroom/students/results.html
{% extends 'base2.html' %}

{% block content %}
<h2>Results</h2>
<p class="text-muted">
  Subjects:{% for subject in user.student.interests.all %} {{ subject.get_html_badge }}{% endfor %}
  <a href="{% url 'students:student_interests' %}"><small>(update interests)</small></a>
</p>
  <p><strong>Name:</strong> {{fname}}  {{lname}}</p>
  <p><strong>Username:</strong> {{username}}</p>
  <p><strong>Test Taken:</strong> {{quiz}}</p>
  <p><strong>Total Questions:</strong> {{total_ques}}</p>
      <div class="card">

        <div class="card-header">

            <div class="row">
            <div class="col-6">
              <strong>Attempted Questions</strong>
            </div>
            <div class="col-4">
              <strong>Your answers</strong>
            </div>
            <div class="col-2">
              <strong>Marks</strong>
            </div>
          </div>
        </div>
        <div class="list-group list-group-flush list-group-formset">
          {% for question,lev,answers,marks in zippedList %}
            <div class="list-group-item">
              <div class="row">
                <div class="col-6">
                  <p>{{question}}<span class="badge badge-pill badge-dark">Level: {{lev}}</span></p>
                </div>
                <div class="col-4">
                  <p>{{answers}}</p>
                </div>
                <div class="col-2">
                  <p>{{marks}}</p>
                </div>

              </div>
            </div>

          {% endfor %}
        </div>
      </tbody>
      </div>
      <p></p>
      <p> <strong>Total Marks Obtained:</strong> {{score}}</p>
      <p> <strong>Total Marks:</strong> {{total_score}}</p>
      <p> <strong>Percentage Obtained:</strong> {{percentage}}%</p>

{% endblock %}

Anlz_app/templates/classroom/students/results_graph.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Graphical Analysis</title>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>
<body>
  <div class="jumbotron">
  <h1 class="display-6">GRAPHICAL ANALYSIS</h1>
    <hr class="my-4">
  <p class="lead"><b>Name: </b>{{fname}} {{lname}}</p>
  <p>Total Questions: {{total_ques}}</p>
  <p>Obtained Marks: {{score}}</p>
  <p>Total Marks Attempted: {{total_score}}</p>
  <p>Attempted Test: {{quiz}}</p>
  <hr class="my-4">
  <div id="graph1"></div>
  <script>
    Highcharts.chart('graph1', {
        chart: {
            type: 'line'
        },
        title: {
            text: 'Level Adaptation Based on Previous Answers'
        },
        xAxis: {
          tickInterval: 1,
          floor:  1,
          softMax: 10,
          title: {
              text: 'Questions'
          },

        },
        yAxis: {
          floor:  1,
          ceiling: 5,
          softMax: 5,

          title: {
              text: 'Level'
          },
      },
        series: [{
            pointStart: 1,
            name: 'Level ',
            data: {{answer_questions_lev}}

        }]
    });
  </script>
<hr class="my-4">
<div id="graph2"></div>
  <script>
  Highcharts.chart('graph2', {
      chart: {
          type: 'line'
      },
      title: {
          text: 'Total Marks Obtained After Each Questions'
      },
      xAxis: {
        floor:  1,
        tickInterval: 1,
        title: {
            text: 'Questions'
        },

      },
      yAxis: {
        title: {
            text: 'Marks'
        },
    },
      series: [{
          pointStart: 1,
          name: 'Total Marks obtained after attempting this question',
          data: {{marks_graph}}

      }]
  });
  </script>
  <hr class="my-4">
  <div id="graph3"></div>
    <script>
    Highcharts.chart('graph3', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Achieved Marks on each Questions'
        },
        xAxis: {
          tickInterval: 1,
          floor:  1,
          title: {
              text: 'Questions'
          },

        },
        yAxis: {

          title: {
              text: 'Marks'
          },
      },
        series: [{
            pointStart: 1,
            name: 'Marks',
            data: {{Marks}}

        }]
    });
    </script>
</body>
</html>

Anlz_app/templates/classroom/students/take_quiz_form.html
{% extends 'base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <div class="progress mb-3">
    <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
  </div>
  <h2 class="mb-3">{{ quiz.name }}</h2>
  <p class="lead">{{ question.text }} </p>


  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Next →</button>
  </form>
{% endblock %}

Anlz_app/templates/classroom/students/taken_quiz_list.html
{% extends 'base2.html' %}

{% block content %}
  {% include 'classroom/students/_header.html' with active='taken' %}
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Test</th>
          <th>Subject</th>
          <th>Percentage</th>
          <th>Total marks Attempted</th>
          <th>Obtained marks</th>
          <th>Results</th>

        </tr>
      </thead>
      <tbody>
        {% for taken_quiz in taken_quizzes %}
          <tr>
            <td>{{ taken_quiz.quiz.name }}</td>
            <td>{{ taken_quiz.quiz.subject.get_html_badge }}</td>
            <td>{{ taken_quiz.score }}</td>
            <td>{{ taken_quiz.total_marks }}</td>
            <td>{{ taken_quiz.obtained_marks}}</td>
            <td><a href="{% url 'students:results' pk=taken_quiz.quiz_id %}" class="btn btn-primary mb-3" role="button">Details</a></td>
              <td><a href="{% url 'students:charts' pk=taken_quiz.quiz_id %}" class="btn btn-primary mb-3" role="button">Graphical Analysis</a></td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="3">You haven't completed any test yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}