Anlz_app/urls.py
from django.urls import include, path

from .views import classroom, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('students/', include(([
        path('', students.QuizListView.as_view(), name='quiz_list'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('quiz/<int:pk>/', students.take_quiz, name='take_quiz'),
        path('taken/<int:pk>/results/',students.view_results,name='results'),
        path('taken/<int:pk>/results/charts/',students.results_graph,name='charts'),
    ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.QuizListView.as_view(), name='quiz_change_list'),
        path('students/activate',teachers.StudentListView.as_view(),name='new_student'),
        path('students/activate/<int:pk>/',teachers.approve,name='approve'),
        path('quiz/add/', teachers.QuizCreateView.as_view(), name='quiz_add'),
        path('quiz/<int:pk>/', teachers.QuizUpdateView.as_view(), name='quiz_change'),
        path('quiz/<int:pk>/delete/', teachers.QuizDeleteView.as_view(), name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:pk>/question/add/', teachers.question_add, name='question_add'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/', teachers.question_change, name='question_change'),
        path('quiz/<int:quiz_pk>/question/<int:question_pk>/delete/', teachers.QuestionDeleteView.as_view(), name='question_delete'),
        path('subject/', teachers.SubjectListView.as_view(), name='sub_list'),
        path('subject/add/',teachers.SubjectCreateView.as_view(),name = 'sub_add'),
        path('subject/del/<int:pk>/',teachers.SubjectDeleteView.as_view(),name = 'sub_del'),
    ], 'classroom'), namespace='teachers')),
]

Stu_Anlz/urls.py
from django.contrib import admin
from django.urls import include, path,re_path

from Anlz_app.views import classroom, students, teachers
from forum.views import contact_us
from Anlz_app import viewss

urlpatterns = [

    path('',viewss.index,name = 'homepage'),
    path('admin/', admin.site.urls),
    path('anlz/', include('Anlz_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    re_path(r'^forum/',include('forum.urls',namespace='forum')),
    re_path(r'^contact_us',contact_us,name='contact'),
    path('', include('django.contrib.flatpages.urls')),
    path('admin1/',classroom.UserListView.as_view(),name='admin_page'),
    path('admin1/approve/<int:pk>/',classroom.approve,name='approve')
]

forum/urls.py
from . import views
from django.urls import re_path

app_name = "forum"
urlpatterns = [
    re_path(r'^$',views.index,name='index'),
    re_path(r'^thread/(?P<pk>\d+)/$', views.view_thread, name='thread'),
    re_path(r'^thread/(?P<pk>\d+)/add_post/$', views.add_post, name='add_post'),
    re_path(r'^create_forum/$', views.create_forum, name='create_forum'),
    re_path(r'^(?P<pk>\d+)/$', views.forum, name='forum'),
    re_path(r'^(?P<pk>\d+)/add_thread/$', views.add_thread, name='add_thread'),
    re_path(r'^thread/post/(?P<pk>\d+)/comment/$', views.comment, name="comment"),
    re_path(r'^(?P<pk>\d+)/edit/$', views.edit_forum, name="edit_forum"),

]

templates/admin_page.html
{% extends 'base2.html' %}

{% block content %}

  <h2 class="mb-3">Activate teachers</h2> <p>Click on any user to activate the user.</p>

  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>All Users</th>

          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for users in User.all %}
        {% if users.is_teacher %}
        {% if not users.is_active %}
          <tr>
            <td class="align-middle"><a href="{% url 'approve' pk=users.pk %}">{{users.username}}</a></td>
          {% endif %}
          {% endif %}
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">No users</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/base2.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Progress Analyzer{% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Clicker+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontello-2f186091/css/fontello.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">

    {% if user.is_authenticated and user.is_teacher %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/teachers.css' %}">
    {% else %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/students.css' %}">
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top" >
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{% static 'images/logo.png'%}">Student Progress Analyzer
          {% if user.is_authenticated %}
            {% if user.is_teacher %}
              <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
            {% else %}
              <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
            {% endif %}
          {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage' %}">Home</a></li>
            <li class="nav-item dropdown">
              {% if user.is_authenticated %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <strong>{{ user.username }}</strong> </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {% if user.is_teacher %}
                    <a class="dropdown-item" href="{% url 'teachers:quiz_change_list' %}">Test List</a>
                  {% else %}
                    <a class="dropdown-item" href="{% url 'students:quiz_list' %}">Take Test</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
                  {% else %}
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Login
           </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <a class="dropdown-item" href="{% url 'login' %}">User Login</a>


             <a class="dropdown-item" href="{% url 'signup' %}">Register</a>
              </div>
              {% endif  %}
           </li>
          <li class="nav-item ">
            <a class="nav-link" href="/about_us">About</a></li>
          <li class="nav-item ">
            <a class="nav-link" href={% url 'forum:index' %}>Forum</a></li>
            <li class="nav-item ">
            <a class="nav-link" href={% url 'contact' %}>Contact Us</a></li>
      </div>
    </div>
  </nav>

    <div class="container my-4">
      <div class="row justify-content-center">
        <div class="col-md-10 col-sm-12">
          <div class="row">
            <div class="col-6">
              <h1 class="logo">
                <a href="{% url 'home' %}">
                  Analyzer
                  {% if user.is_authenticated %}
                    {% if user.is_teacher %}
                      <span class="icon-feather" data-toggle="tooltip" data-placement="right" title="Teacher profile"></span>
                    {% else %}
                      <span class="icon-graduation-cap" data-toggle="tooltip" data-placement="right" title="Student profile"></span>
                    {% endif %}
                  {% endif %}
                </a>
              </h1>
            </div>
            <div class="col-6 text-right">
              {% if user.is_authenticated %}
                <p class="pt-3">Logged in as <strong>{{ user.username }}</strong>. <a href="{% url 'logout' %}">Log out</a>.</p>
              {% else %}
                <a href="{% url 'login' %}" class="btn btn-light" role="button">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary" role="button">Sign up</a>
              {% endif %}
            </div>
          </div>
          <div class="card mb-3">
            <div class="card-body">
              {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              {% endfor %}
              {% block content %}
              {% endblock %}
            </div>
          </div>
        </div>
      </div>
    </div>
          <footer>
            <div class="container-fluid padding">
              <div class="row text-center">
                <div class="col-md-4">
                  <img src="{% static 'images/logo.png'%}" alt="">
                  <hr class="light">
                  <p>+977-984-XXXXXX</p>
                  <p>Email@gmail.com</p>
                  <p>Kupondole, Lalitpur</p>
                </div>
                <div class="col-md-4">
                  <hr class="light">
                  <h5>Project links</h5>
                  <hr class="light">

                  <p> <a href="{% url 'home' %}">Home</a></li></p>
                  <p><a href="{% url 'login' %}">Login</a></li></p>
                      <p><a href={% url 'forum:index' %}>Forum</a> </p>
                      <p><a href={% url 'contact' %}>Contact Us</a> </p>


                </div>
            <div class="col-md-4">
              <hr class="light">
              <h5>About Project</h5>
              <hr class="light">
              <p>Track the understanding of the students in different subjects using automated MCQ test.</p>
            </div>
            <div class="col-12">
              <hr class-="light-100">
            </div>
              </div>
          </div>
          </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip();
      })
    </script>
  </body>
</html>

templates/contact_us.html
{% extends "base2.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
      <form method="post">
        <div class="container">
          <div class="alert alert-dark" role="alert">
          We are always open for suggestion
          </div>
  <div class="row">
    <div class="col-sm">
      {{ form.first_name|as_crispy_field }}
        {{ form.last_name|as_crispy_field }}
        {{ form.email|as_crispy_field }}
        {{ form.text|as_crispy_field }}
    </div>
    <div class="col-sm">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.880874980766!2d85.3105445150617!3d27.690076482799128!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb184cde39c699%3A0x9cbf0d6c5419bad8!2sAdvanced+College+of+Engineering+%26+Management!5e0!3m2!1sen!2snp!4v1533725332062" width="400" height="450" frameborder="0" style="border:0" allowfullscreen >ACEM</iframe>
    </div>

  </div>
</div>


        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
      </form>
      <form  method="post">

      </form>
{% endblock content %}